controllers:
    resource: ../../src/Presentation/Controller/Api
    type: annotation

home:
    resource: ../../src/Presentation/Controller
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
