index:
    path: /
    controller: App\Presentation\Controller\WebController::index
controllers:
    resource: ../src/Presentation/Controller/Api/BlogController.php
    type: annotation
    prefix: /api
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }